--- 
application: 
  angularConfig: 
    URL: "http://52.42.88.239:30510/"
eureka: 
  client: 
    service-url: 
      defaultZone: "http://admin:${jhipster.registry.password}@52.40.247.241:30512/eureka/"
  instance: 
    ip-address: "52.40.247.241"
    non-secure-port: 30514
    prefer-ip-address: true
jhipster: 
  http: 
    cache: 
      timeToLiveInDays: 1461
    version: V_1_1
  logging: 
    logstash: 
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
    spectator-metrics: 
      enabled: false
  mail: 
    base-url: "http://52.40.247.241:30314"
    from: cognitivecloud.quinnox@gmail.com
  metrics: 
    graphite: 
      enabled: false
      host: localhost
      port: 2003
      prefix: UserMgmt
    jmx.enabled: true
    logs: 
      enabled: false
      report-frequency: 60
    prometheus: 
      enabled: false
      endpoint: /prometheusMetrics
  security: 
    client-authorization: 
      access-token-uri: "http://uaa/oauth/token"
      client-id: internal
      client-secret: internal
      token-service-id: uaa
liquibase: 
  contexts: prod
server: 
  compression: 
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css, application/javascript, application/json"
    min-response-size: 1024
  port: 8082
spring: 
  data: 
    elasticsearch: 
      cluster-name: ~
      cluster-nodes: ~
      properties: 
        path: 
          data: target/elasticsearch/data
          logs: target/elasticsearch/log
  datasource: 
    hikari: 
      data-source-properties: 
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:mysql://52.40.247.241:30511/usermgmt?useUnicode=true&characterEncoding=utf8&useSSL=false"
    username: root
  devtools: 
    livereload: 
      enabled: false
    restart: 
      enabled: false
  jpa: 
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties: 
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.generate_statistics: false
      hibernate.id.new_generator_mappings: true
    show-sql: false
  mail: 
    host: smtp.gmail.com
    password: Quinnox@123
    port: 587
    properties.mail.smtp: 
      auth: true
      ssl.trust: smtp.gmail.com
      starttls.enable: true
    protocol: smtp
    tls: true
    username: cognitivecloud.quinnox@gmail.com
  messages: 
    cache-seconds: 1
  thymeleaf: 
    cache: true
